name: Release Tag

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  ensure_rust_cargo_toml_version:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: rdna

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Ensure rust cargo toml version
        run: |
          TOML_PACKAGE_VERSION=$(grep "^version = " Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          LOCK_PACKAGE_VERSION=$(grep -A 1 "name = \"${{ env.PACKAGE_NAME }}\"" Cargo.lock | grep "^version = " | head -1 | sed 's/version = "\(.*\)"/\1/')

          CURRENT_TAG=${{ github.ref_name }}

          echo "Repository version ${CURRENT_TAG}"
          echo "Cargo.toml version ${TOML_PACKAGE_VERSION}"
          echo "Cargo.lock version ${LOCK_PACKAGE_VERSION}"

          if [[ "$CURRENT_TAG" != "v$TOML_PACKAGE_VERSION" ]]; then
            echo "Error: Cargo.toml ${TOML_PACKAGE_VERSION} version does not match tag version ${CURRENT_TAG}"
            exit 1
          fi

          if [[ "$CURRENT_TAG" != "v$LOCK_PACKAGE_VERSION" ]]; then
            echo "Error: Cargo.lock ${LOCK_PACKAGE_VERSION} version does not match tag version ${CURRENT_TAG}"
            exit 1
          fi

  create_release:
    needs: [ensure_rust_cargo_toml_version]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload_binaries:
    needs: [ensure_rust_cargo_toml_version, create_release]

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Upload binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bin: rdna
          target: ${{ matrix.target }}
          checksum: sha256
          archive: $bin-$tag-$target
          manifest_path: Cargo.toml
